# Generated by Django 4.2.10 on 2024-12-04 00:23

from django.db import migrations, models
from django.utils.text import slugify

def generate_unique_slugs(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    for category in Category.objects.all():
        counter = 1
        slug = slugify(category.name)
        while Category.objects.filter(slug=slug).exists():
            slug = f"{slugify(category.name)}-{counter}"
            counter += 1
        category.slug = slug
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_certificationlevel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(generate_unique_slugs),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]